sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '8'
  - '7'
  - '6'
before_script:
  - npm prune
script:
  - npm run build
  - npm run test:coverage
after_success:
  - npm run report-coverage
